receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: "0.0.0.0:14250"
      thrift_compact:
        endpoint: "0.0.0.0:6831"
      thrift_http:
        endpoint: "0.0.0.0:14268"
  otlp:
    protocols:
      grpc:
      http:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:
    loglevel: DEBUG

  azuremonitor:
    # endpoint is the uri used to communicate with Azure Monitor
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    # instrumentation_key is the unique identifer for your Application Insights resource
    instrumentation_key: "<your_instrumentation_key>"
    # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
    maxbatchsize: 100
    # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
    maxbatchinterval: 10s

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

  jaeger_thrift:
    url: "http://jaeger-all-in-one:14268/api/traces"
processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  pipelines:
    traces:
      receivers: [jaeger,otlp]
      processors: []
      exporters: [azuremonitor, logging, jaeger_thrift]
#    metrics:
#      receivers: [opencensus]
#      processors: [batch]
#      exporters: [logging,prometheus]

